apiVersion: apps/v1
kind: Deployment
metadata:
  name: promshim-sd
  labels:
    app: promshim-sd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promshim-sd
  template:
    metadata:
      labels:
        app: promshim-sd
    spec:
      serviceAccountName: promshim-sd
      containers:
        - name: app
          image: dennysv/promshim-http-sd:latest
          # ports:
          #   - containerPort: 8000
