apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: promshim-sd-reader
rules:
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["gateway.networking.k8s.io"]
    resources:
      - httproutes
      - grpcroutes
    verbs:
      - get
      - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: promshim-sd
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: promshim-sd-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: promshim-sd-reader
subjects:
  - kind: ServiceAccount
    name: promshim-sd
    namespace: default
